name: "ClickyParticles"
description: "Summon customizable particles when right-clicking other players!"
author: TurtleException
website: "https://github.com/TurtleException/ClickyParticles"

main: de.turtleboi.spigot.clicky_particles.ClickyParticles
version: ${project.version}
api-version: 1.20

commands:
  clicky:
    description: "Opens the particle configurator"
    usage: /clicky
    aliases:
      - click
      - particles
  reload-particles:
    description: "Reload the particles.yml file"
    usage: /reload-particles